#!/usr/bin/env node
// Downloads the brand fonts once and stores them in src/assets/fonts/ so the site
// never depends on Google Fonts at render time (Google domains are blocked in
// mainland China, where a render-blocking request would leave pages blank).
//   node tools/fetch-fonts.mjs
// Output: src/assets/fonts/*.woff2 + src/assets/fonts/fonts.css (@font-face rules,
// urls relative to the built stylesheet in assets/). build.mjs prepends fonts.css
// to the site stylesheet and copies the woff2 files to assets/fonts/.
// Only the subsets the site needs are kept: Latin + Latin Extended for Archivo and
// Inter, Arabic for IBM Plex Sans Arabic. Chinese pages use the visitor's system
// CJK fonts (PingFang SC, Microsoft YaHei, Noto Sans CJK SC…), so no CJK web font.
// Fonts are licensed under the SIL Open Font License 1.1.
import fs from 'node:fs';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const OUT = path.join(ROOT, 'src', 'assets', 'fonts');
const UA = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36';
const FAMILIES = [
  { q: 'Archivo:wdth,wght@62..125,500..800', slug: 'archivo', subsets: ['latin', 'latin-ext'] },
  { q: 'Inter:wght@400;500;600', slug: 'inter', subsets: ['latin', 'latin-ext'] },
  { q: 'IBM+Plex+Sans+Arabic:wght@400;500;600;700', slug: 'plex-arabic', subsets: ['arabic'], perWeight: true },
];
const curl = (url) => execFileSync('curl', ['-sSfL', '--compressed', '-A', UA, '--max-time', '60', url], { maxBuffer: 64 * 1024 * 1024 });

fs.mkdirSync(OUT, { recursive: true });
for (const f of fs.readdirSync(OUT)) if (f.endsWith('.woff2')) fs.rmSync(path.join(OUT, f));
const rules = [];
let total = 0;
for (const fam of FAMILIES) {
  const css = curl(`https://fonts.googleapis.com/css2?family=${fam.q}&display=swap`).toString('utf8');
  const blocks = [...css.matchAll(/\/\*\s*([\w-]+)\s*\*\/\s*@font-face\s*\{([^}]*)\}/g)];
  const seen = new Map();
  for (const [, subset, body] of blocks) {
    if (!fam.subsets.includes(subset)) continue;
    const url = (body.match(/url\((https:[^)]+\.woff2)\)/) || [])[1];
    const weight = (body.match(/font-weight:\s*([^;]+);/) || [])[1].trim();
    if (!url) continue;
    let file = seen.get(url);
    if (!file) {
      file = `${fam.slug}-${subset}${fam.perWeight ? '-' + weight : ''}.woff2`;
      const buf = curl(url);
      fs.writeFileSync(path.join(OUT, file), buf);
      total += buf.length;
      seen.set(url, file);
      console.log(`  ${file.padEnd(34)} ${(buf.length / 1024).toFixed(1)} KB`);
    }
    const clean = body.replace(/src:[^;]+;/, `src: url("fonts/${file}") format("woff2");`).replace(/\s+/g, ' ').trim();
    rules.push(`/* ${fam.slug} ${subset} ${weight} */\n@font-face { ${clean} }`);
  }
}
fs.writeFileSync(path.join(OUT, 'fonts.css'), `/* Self-hosted fonts (SIL Open Font License 1.1), generated by tools/fetch-fonts.mjs. Do not edit. */\n${rules.join('\n')}\n`);
console.log(`Wrote src/assets/fonts/fonts.css (${rules.length} rules), ${(total / 1024).toFixed(0)} KB of woff2.`);
